# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/devops.kubesphere.io_pipelines.yaml
- bases/devops.kubesphere.io_devopsprojects.yaml
- bases/devops.kubesphere.io_s2ibinaries.yaml
- bases/devops.kubesphere.io_s2ibuilders.yaml
- bases/devops.kubesphere.io_s2ibuildertemplates.yaml
- bases/devops.kubesphere.io_s2iruns.yaml
- bases/devops.kubesphere.io_pipelineruns.yaml
- bases/devops.kubesphere.io_templates.yaml
- bases/devops.kubesphere.io_clustertemplates.yaml
- bases/devops.kubesphere.io_addons.yaml
- bases/devops.kubesphere.io_addonstrategies.yaml
- bases/gitops.kubesphere.io_applications.yaml
- bases/devops.kubesphere.io_gitrepositories.yaml
- bases/devops.kubesphere.io_webhooks.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_pipelines.yaml
#- patches/webhook_in_fakes.yaml
#- patches/webhook_in_pipelineruns.yaml
#- patches/webhook_in_templates.yaml
#- patches/webhook_in_clustertemplates.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_pipelines.yaml
#- patches/cainjection_in_fakes.yaml
#- patches/cainjection_in_pipelineruns.yaml
#- patches/cainjection_in_templates.yaml
#- patches/cainjection_in_clustertemplates.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
