name: API Testing

on:
  push:
    branches:
    - master
    - apitest

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Init Env
        run: |
          curl -L https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.67/hd-linux-amd64.tar.gz | tar xzv hd
          sudo mv hd /usr/bin/hd
          
          hd i k3d
          hd i atest
          k3d cluster create
          
          kubectl apply -k config/default --wait=true
          kubectl wait deployment -n kubesphere-devops-system ks-devops-devops-apiserver --for condition=Available=True --timeout=900s
          kubectl get all --all-namespaces
      - name: Run Test
        run: |
          atest run -p 'test/api/*.yaml'
